#' Functions to load data from banks
#'
#' @details This functions are adjusted \code{\link[utils]{read.table}} function
#' to load specific CSV files generated by various banks. Banks currently supported:
#' \itemize{
#' \item{mBank}{\code{mbank}}
#' \item{Idea Bank}{\code{idea}}
#' }
#'
#' @param file path to file with transaction data
#' @param bank character with bank name, see Details for supported banks
#' @param ... optional arguments passed to \code{\link[utils]{read.table}}
#'
#' @author Daniel Rodak
#' @export
readBank <- function(file, bank, ...) {
  if(!(bank %in% CNSTsupportedBanks)) {
    stop(bank, " is not supported. Contact with ", maintainer("budgetr"))
  }
  read.fun <- switch(
    bank,
    mbank = readMbank,
    idea = readIdea)
  return(read.fun(file, ...))
}

readMbank <- function(file, ...) {
  tbl <- read.table(file, header = TRUE, sep = ";", dec = ",",
                    quote = "\"", fill = TRUE, comment.char = "",
                    skip = 37, stringsAsFactors = FALSE, ...)
  tbl <- tbl[1:(nrow(tbl) - 2), c(2, 3, 4, 5, 7)]
  colnames(tbl) <- c("Date", "Type", "Title", "Payee", "Amount")
  tbl$Date <- as.Date(tbl$Date)
  tbl$Amount <- as.numeric(gsub(",", ".", gsub(" ", "", tbl$Amount)))
  return(tbl)
}

readIdea <- function(file, ...) {
  tbl <- read.table(file, header = TRUE, sep = ";", dec = ",",
                    quote = "\"", fill = TRUE, comment.char = "",
                    skip = 1, stringsAsFactors = FALSE,
                    fileEncoding = 'UTF-8', ...)
  tbl <- tbl[, c(2, 16, 15, 10, 5)]
  colnames(tbl) <- c("Date", "Type", "Title", "Payee", "Amount")
  tbl$Date <- as.Date(as.character(tbl$Date), "%Y%m%d")
  tbl$Amount <- ifelse(tbl$Type == 'uznanie', -1, 1) * tbl$Amount
  return(tbl)
}
