#' Load data from QIF file generated by MicroSoft Money
#'
#' @param file path to file with QIF transaction data
#'
#' @author Daniel Rodak
#' @export
readQIF <- function(file, ...) {
  stopifnot(file.exists(file))
  con <- file(file)
  on.exit(close(con))
  ln <- readLines(con)
  ln <- ln[!grepl("^!", ln)]
  delims <- grep("^\\^", ln)
  delims <- c(0, delims)
  lnlist <- lapply(2:length(delims), function(i) ln[(delims[i - 1] + 1):(delims[i] - 1)])
  ret <- do.call(rbind, lapply(lnlist, parseQIFLine))
  return(ret)
}

#' Parse single QIF line
parseQIFLine <- function(x) {
  stopifnot(all(c(any(grepl("^D", x)), any(grepl("^P", x)), any(grepl("^T", x)))))

  date <- as.Date(substring(grep("^D", x, value = TRUE), 2))
  title <- substring(grep("^M", x, value = TRUE), 2)
  payee <- substring(grep("^P", x, value = TRUE), 2)
  amount <- substring(grep("^T", x, value = TRUE), 2)
  amount <- as.numeric(gsub(",", "", amount))
  type <- ifelse(sign(amount) < 0, "Przelew Wychodzący", "Przelew Przychodzący")
  category <- substring(grep("^L", x, value = TRUE), 2)
  title <- ifelse(length(title) == 0, "", title)
  category <- ifelse(length(category) == 0, "", category)

  return(data.frame(
    Date = date,
    Type = type,
    Title = title,
    Payee = payee,
    Amount = amount,
    Category = category,
    stringsAsFactors = FALSE
  ))
}
